//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_config_value
    {
        public long id { get; set; }
        public string configstring { get; set; }
        public string configtype { get; set; }
        public sbyte active { get; set; }
        public System.DateTime createdon { get; set; }
        public string ResponseQueue { get; set; }
        public string RequestQueue { get; set; }
        public string FileName { get; set; }
    }
}
