//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_initiation_tracker
    {
        public long id { get; set; }
        public string request_id { get; set; }
        public string req_date { get; set; }
        public string candidate_id { get; set; }
        public string associate_id { get; set; }
        public string bgv_type { get; set; }
        public string package { get; set; }
        public string account { get; set; }
        public string name { get; set; }
        public string allocated_to { get; set; }
        public string docs_download { get; set; }
        public string status { get; set; }
        public string crn { get; set; }
        public string creation_date { get; set; }
        public string drug_panel { get; set; }
        public string req_date1 { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
