//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_document_data
    {
        public decimal Document_Data_Entry_ID { get; set; }
        public decimal RequestID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public int Document_Version { get; set; }
        public Nullable<int> Data_Sequence { get; set; }
        public string JSON_Data { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public sbyte PartitionKey { get; set; }
    }
}
