//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mislog_count
    {
        public long id { get; set; }
        public string filePath { get; set; }
        public Nullable<long> rowscount { get; set; }
        public System.DateTime createdOn { get; set; }
    }
}
