//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sbu_master
    {
        public long SBUID { get; set; }
        public string SBU_Name { get; set; }
        public Nullable<long> ClientID { get; set; }
    }
}
