//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_yettostart_casecreation_data
    {
        public long id { get; set; }
        public Nullable<long> queue_request_id { get; set; }
        public string cognizent_tech_solution { get; set; }
        public string clientcode { get; set; }
        public string candidate_name { get; set; }
        public string client_ref_no { get; set; }
        public string bvg_type { get; set; }
        public string package { get; set; }
        public string specification { get; set; }
        public string project_id { get; set; }
        public string project_name { get; set; }
        public string doj { get; set; }
        public string request_id { get; set; }
        public string associate_id { get; set; }
        public string candidate_id { get; set; }
        public string employee_id { get; set; }
        public string account_name { get; set; }
        public string tensse { get; set; }
        public string actual_case_created { get; set; }
        public string college_ut { get; set; }
        public string college_cvt { get; set; }
        public string degree_type_ut { get; set; }
        public string degree_type_cvt { get; set; }
        public string reference_type_ut { get; set; }
        public string reference_type_cvt { get; set; }
        public string company_name_ut { get; set; }
        public string company_name_cvt { get; set; }
        public string id_ut { get; set; }
        public string id_cvt { get; set; }
        public string employment_type_ut { get; set; }
        public string employment_type_cvt { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string date_of_birth { get; set; }
        public string father_name { get; set; }
        public string nationality { get; set; }
        public string mobile_number { get; set; }
        public string current_address { get; set; }
        public string permanent_address { get; set; }
        public string longest_stay_address { get; set; }
        public sbyte active { get; set; }
        public System.DateTime createdOn { get; set; }
        public string LOA_Status { get; set; }
        public Nullable<long> responseId { get; set; }
        public Nullable<long> ExpressRequestID { get; set; }
        public string PG_University { get; set; }
        public string Prev_Employment_Type { get; set; }
        public string Prev_Employee_Phone { get; set; }
        public string Prev_Supervisor_Home_manager_Title { get; set; }
        public string Prev_Supervisor_Home_manager_Email { get; set; }
        public string Prev_HR_Name { get; set; }
        public string Prev_HR_Phone { get; set; }
        public string Prev_Zipcode { get; set; }
        public string Prev_Leaving_Reason { get; set; }
        public string Prev_city { get; set; }
        public string Prev_Employee_Id { get; set; }
        public string Prev_Fax_No { get; set; }
        public string Prev_Supervisor_Home_Manager_Name { get; set; }
        public string Prev_Supervisor_Home_Manager_Phone { get; set; }
        public string Prev_HR_Email { get; set; }
        public string GAP_Reason { get; set; }
        public string Prev_Role_Description { get; set; }
        public string GapBetween { get; set; }
        public string Gap_Address { get; set; }
        public string Professional_Reference_Name { get; set; }
        public string Professional_Reference_Designation { get; set; }
        public string Professional_Reference_Email { get; set; }
        public string Professional_Reference_Company_Name { get; set; }
        public string Professional_Reference_Mobile { get; set; }
        public string Professional_Reference_ID { get; set; }
        public string Other_Address_Address_Line1 { get; set; }
        public string Other_Address__Address_Line2 { get; set; }
        public string Other_Address_City { get; set; }
        public string Other_Address_Country_Name { get; set; }
        public string Other_Address_Nature_Location { get; set; }
        public string Other_Address_State { get; set; }
        public string Other_Address_Pincode { get; set; }
        public string Other_Address_ID { get; set; }
        public string Other_Address_Time_Period { get; set; }
        public string Previous_Principle_Company { get; set; }
        public string Previos_Principle_Company_Address { get; set; }
        public string CVT_Identity { get; set; }
        public string CVT_Database_OIG { get; set; }
        public string CVT_Database_GSA { get; set; }
        public string CVT_Court_Check { get; set; }
        public string CVT_Drug_Test { get; set; }
        public string CVT_Tennessee { get; set; }
        public string CVT_Court_Date { get; set; }
        public string CVT_Previous_Employment_Company { get; set; }
        public string CVT_Previous_Employment { get; set; }
        public string CVT_CurrentEmployment_Company { get; set; }
        public string CVT_Current_Employment { get; set; }
        public string CVT_Mandatory_Court_Address { get; set; }
        public string CVT_Mandatory_Address { get; set; }
        public string CVT_GAP_Type { get; set; }
        public string CVT_GAP_Address { get; set; }
        public string CVT_GAP_Between { get; set; }
        public string CVT_Address_ID { get; set; }
        public string CVT_Address_Duration { get; set; }
        public string CVT_Professional_ID { get; set; }
        public string CVT_Professional_Company { get; set; }
        public string CVT_Facis { get; set; }
        public string CVT_NSR { get; set; }
        public string CVT_SAM { get; set; }
        public string CVT_OFAC { get; set; }
        public string Diploma_CVT_Type { get; set; }
        public string Diploma_CVT_Deatils { get; set; }
        public string Twelve_CVT_Type { get; set; }
        public string Twelve_CVT_Details { get; set; }
        public string Tenth_CVT_Type { get; set; }
        public string Tenth_CVT_Details { get; set; }
        public string Longest_Stay_Address_UT { get; set; }
        public string Diploma_UT_DegreeType { get; set; }
        public string Diploma_UT_EducationPeriod { get; set; }
        public string Diploma_UT_College { get; set; }
        public string Diploma_UT_University { get; set; }
        public string Diploma_UT_Percentage { get; set; }
        public string Diploma_UT_Education_Type { get; set; }
        public string Longest_Stay_Address_POS_UT { get; set; }
        public string UT_Permanent_Address_POS { get; set; }
        public string tbl_yettostart_casecreation_datacol { get; set; }
        public string UT_Current_Address_POS { get; set; }
        public string UT_Nature_Of_Location_Current { get; set; }
        public string UT_Nature_Of_Location_Permanent { get; set; }
    }
}
