//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_input_request_data
    {
        public long Id { get; set; }
        public Nullable<long> ImportKey { get; set; }
        public string Request_ID { get; set; }
        public string Candidate_ID { get; set; }
        public string Associate_Id { get; set; }
        public string BGV_Type { get; set; }
        public string Name { get; set; }
        public string DOJ { get; set; }
        public string BU { get; set; }
        public string Department { get; set; }
        public string Account_Group { get; set; }
        public string Account { get; set; }
        public string Project { get; set; }
        public string Components { get; set; }
        public string Pre_BGV_Initiated_Date { get; set; }
        public string CE_BGV_Initiated_Date { get; set; }
        public string CE_Available { get; set; }
        public string Vendor_Status { get; set; }
        public string Additional_Payment_Status { get; set; }
        public string HR_POC { get; set; }
        public string Work_Location { get; set; }
        public string Report_uploaded_date { get; set; }
        public string Last_Updated_On { get; set; }
        public sbyte Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
