//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_response_detail
    {
        public long id { get; set; }
        public Nullable<long> request_id { get; set; }
        public string response_json { get; set; }
        public Nullable<sbyte> status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string message_id { get; set; }
        public string service_id { get; set; }
    }
}
