//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_exception_log
    {
        public long Id { get; set; }
        public string exception_log { get; set; }
        public string function_name { get; set; }
        public System.DateTime create_date { get; set; }
    }
}
