//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_college_details
    {
        public long id { get; set; }
        public Nullable<long> reqid { get; set; }
        public Nullable<long> resid { get; set; }
        public string college { get; set; }
        public string degree { get; set; }
        public string field_source { get; set; }
        public sbyte active { get; set; }
        public System.DateTime createdon { get; set; }
    }
}
