//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_requests
    {
        public decimal RequestID { get; set; }
        public Nullable<decimal> Parent_RequestID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string CRN_Number { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Client_Ref_No { get; set; }
        public Nullable<System.DateTime> Case_Date { get; set; }
        public string Subject_Detail { get; set; }
        public string Subject_Type { get; set; }
        public Nullable<sbyte> Is_Date_of_Birth { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Type_Of_Check { get; set; }
        public string Candidate_Authorization_Letter { get; set; }
        public string Package_Type { get; set; }
        public string Srt_Data { get; set; }
        public System.DateTime Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<long> SBUID { get; set; }
        public string LOA_Submitted { get; set; }
        public string BVF_Submitted { get; set; }
        public Nullable<System.DateTime> CRN_CreateDate { get; set; }
        public sbyte PartitionKey { get; set; }
        public string JSON_Data { get; set; }
        public string status_message { get; set; }
        public Nullable<long> DEPENDENT_CHILD_ID { get; set; }
        public string Request_Type { get; set; }
        public string Status_Type { get; set; }
        public string Remarks { get; set; }
    }
}
