//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Utility
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fadv_touchlessEntities : DbContext
    {
        public fadv_touchlessEntities()
            : base("name=fadv_touchlessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_initiation_tracker> tbl_initiation_tracker { get; set; }
        public virtual DbSet<tbl_input_request_data> tbl_input_request_data { get; set; }
        public virtual DbSet<tbl_exception_log> tbl_exception_log { get; set; }
        public virtual DbSet<tbl_request_details> tbl_request_details { get; set; }
        public virtual DbSet<tbl_college_details> tbl_college_details { get; set; }
        public virtual DbSet<tbl_config_value> tbl_config_value { get; set; }
        public virtual DbSet<tbl_response_detail> tbl_response_detail { get; set; }
        public virtual DbSet<tbl_yettostart_casecreation_data> tbl_yettostart_casecreation_data { get; set; }
        public virtual DbSet<tbl_mislog_count> tbl_mislog_count { get; set; }
        public virtual DbSet<tbl_request_tracker> tbl_request_tracker { get; set; }
        public virtual DbSet<tbl_requests> tbl_requests { get; set; }
        public virtual DbSet<tbl_sbu_master> tbl_sbu_master { get; set; }
        public virtual DbSet<tbl_request_state_instance> tbl_request_state_instance { get; set; }
        public virtual DbSet<tbl_document_upload> tbl_document_upload { get; set; }
    }
}
