//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_request_state_instance
    {
        public decimal RequestID { get; set; }
        public int Sequence { get; set; }
        public string StateID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string Comments { get; set; }
        public Nullable<sbyte> Is_Current { get; set; }
        public Nullable<sbyte> IS_Review { get; set; }
        public sbyte PartitionKey { get; set; }
    }
}
