//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_yettostart_casecreation_data
    {
        public long id { get; set; }
        public Nullable<long> queue_request_id { get; set; }
        public string cognizent_tech_solution { get; set; }
        public string clientcode { get; set; }
        public string candidate_name { get; set; }
        public string client_ref_no { get; set; }
        public string bvg_type { get; set; }
        public string package { get; set; }
        public string specification { get; set; }
        public string project_id { get; set; }
        public string project_name { get; set; }
        public string doj { get; set; }
        public string request_id { get; set; }
        public string associate_id { get; set; }
        public string candidate_id { get; set; }
        public string employee_id { get; set; }
        public string account_name { get; set; }
        public string tensse { get; set; }
        public string actual_case_created { get; set; }
        public string college_ut { get; set; }
        public string college_cvt { get; set; }
        public string degree_type_ut { get; set; }
        public string degree_type_cvt { get; set; }
        public string reference_type_ut { get; set; }
        public string reference_type_cvt { get; set; }
        public string company_name_ut { get; set; }
        public string company_name_cvt { get; set; }
        public string id_ut { get; set; }
        public string id_cvt { get; set; }
        public string employment_type_ut { get; set; }
        public string employment_type_cvt { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string date_of_birth { get; set; }
        public string father_name { get; set; }
        public string nationality { get; set; }
        public string mobile_number { get; set; }
        public string current_address { get; set; }
        public string permanent_address { get; set; }
        public string longest_stay_address { get; set; }
        public sbyte active { get; set; }
        public System.DateTime createdOn { get; set; }
        public string LOA_Status { get; set; }
        public Nullable<long> responseId { get; set; }
    }
}
