//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_request_details
    {
        public long id { get; set; }
        public string messageid { get; set; }
        public string json_text { get; set; }
        public string request_type { get; set; }
        public System.DateTime createdOn { get; set; }
        public int Status { get; set; }
    }
}
